{
  "openapi": "3.0.0",
  "info":{
    "title": "Challenge 3",
    "version":"1.0",
    "description": ""
  },
  "tags":[
    {
      "name": "Login",
      "description": "Get the authentication token"
    },{
      "name": "Tutor",
      "description": "features to handle tutor(s)"
    },{
      "name": "Pet",
      "description": "features to handle pet(s)"
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "tags": ["Login"],
        "summary": "Authenticate the user.",
        "requestBody": {
          "description": "Tutor credentials",
          "requery": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Auth"
              }
            }
          }
        },
        "responses":{
          "200": {
            "description": "Successful authentication!"
          },
          "400": {
            "description": "Invalid email or password"
          },
          "401": {
            "description": "Invalid email or password"
          },
          "404": {
            "description": "User not found!"
          },
          "422": {
            "description": "Email and password is required!"
          }
        }
      }
    },
    "/tutor": {
      "post": {
        "tags": ["Tutor"],
        "summary": "Create a new tutor",
        "requestBody": {
          "description": "Data for a new tutor",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Tutor"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Tutor created successfully!"
          },
          "400": {
            "description": "Request error"
          }
        }
      }
    },
    "/tutors": {
      "get": {
        "tags": ["Tutor"],
        "summary": "Retrieves all tutors.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Listing All Tutors and Pets",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Tutor"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error"
          },
          "401": {
            "description": "Authentication invalid, unauthorized"
          }
        }
      }
    },
    "/tutor/{id}": {
      "get":{
        "tags": ["Tutor"],
        "summary": "Get specific tutor",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "security":[
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Tutor data",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Tutor"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error"
          },
          "401": {
            "description": "Authentication invalid, unauthorized"
          }
        }
      },
      "put": {
        "tags": ["Tutor"],
        "summary": "Updates a tutor",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "description": "New data for the tutor",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PutTutor"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Tutor updated successfully"
          },
          "400": {
            "description": "Request error"
          },
          "401": {
            "description": "Authentication invalid, unauthorized"
          },
          "404": {
            "description": "Tutor not found"
          }
        }
      },
      "delete": {
        "tags": ["Tutor"],
        "summary": "Deletes a tutor",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "204": {
            "description": "Tutor deleted successfully"
          },
          "400": {
            "description": "Request error"
          },
          "401": {
            "description": "Authentication invalid, unauthorized"
          },
          "403": {
            "description": "Tutor has pets associated"
          },
          "404": {
            "description": "Tutor not found"
          }
        }
      }
    },

    "/pet": {
      "get": {
        "tags": ["Pet"],
        "summary": "Retrieves all pets.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Listing All Pets",
            "content": {
              "application/json": {
                "schema": {
                  "type":"array",
                  "items": {
                    "$ref":"#/components/schemas/Pet"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Request error"
          },
          "401": {
            "description": "Authentication invalid, unauthorized"
          }
        }
      }
    },
    "/pet/{petId}": {
      "get": {
        "tags": ["Pet"],
        "summary": "Get specific pet",
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "requery": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Pet data",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref":"#/components/schemas/Pet"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Request error"
          },
          "401": {
            "description": "Authentication invalid, unauthorized"
          },
          "404": {
            "description": "Pet not found"
          }
        }
      }
    },
    "/pet/{tutorId}": {
      "post": {
        "tags": ["Pet"],
        "summary": "Creates a pet and adds it to a tutor",
        "parameters": [
          {
            "name": "tutorId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "description": "Data for a new pet",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Pet created and associated with tutor successfully"
          },
          "400": {
            "description": "Request error"
          },
          "401": {
            "description": "Authentication invalid, unauthorized"
          },
          "404": {
            "description": "Tutor not found"
          }
        }
      }
    },
    "/pet/{petId}/tutor/{tutorId}": {
      "put": {
        "tags": ["Pet"],
        "summary": "Updates a pet's info",
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "tutorId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "description": "New data for the pet",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PutPet"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Pet updated"
          },
          "400": {
            "description": "Request error"
          },
          "401": {
            "description": "Authentication invalid, unauthorized"
          },
          "404": {
            "description": "Pet not found"
          }
        }
      },
      "delete": {
        "tags": ["Pet"],
        "summary": "Deletes a pet from a tutor",
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "tutorId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "204": {
            "description": "Pet deleted successfully"
          },
          "400": {
            "description": "Request error"
          },
          "401": {
            "description": "Authentication invalid, unauthorized"
          },
          "404": {
            "description": "Tutor or Pet not found"
          }
        }
      }
    }
  },
  "components": {
    "schemas":{
      "Auth": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "format": "email"
          },
          "password": {
            "type": "string",
            "format": "password"
          }
        },
        "example": {
          "email": "adm@gmail.com",
          "password": "adm12345"
      },
        "required": [
          "email",
          "password"
        ]
      },
      "AuthResponse": {
        "type":"object",
        "properties": {
          "token": {
            "type": "string"
          }
        }
      },
      "Tutor": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "password": {
            "type": "string",
            "format": "password"
          },
          "phone": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "date_of_birth": {
            "type": "string",
            "format": "date"
          },
          "zip_code": {
            "type": "string"
          },
          "pets": {
            "type": "array"
          }
        },
        "example": {
          "name": "user",
          "password": "12345678" ,
          "phone": "40028922",
          "email": "user@gmail.com",
          "date_of_birth": "2023-12-12 10: 10" ,
          "zip_code": "12345678" 
      },  
        "required": [
          "name",
          "password",
          "phone",
          "email",
          "date_of_birth",
          "zip_code",
          "pets"
          
        ]
      },
      "PutTutor": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "password": {
            "type": "string",
            "format": "password"
          },
          "phone": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "date_of_birth": {
            "type": "string",
            "format": "date"
          },
          "zip_code": {
            "type": "string"
          },
          "pets": {
            "type": "array"
          }
        },
        "example": {
          "name": "User01",
          "password": "12345678" ,
          "phone": "40028922",
          "email": "User01@gmail.com",
          "date_of_birth": "2023-12-12 10: 10" ,
          "zip_code": "12345678" 
      },  
        "required": [
          "name",
          "password",
          "phone",
          "email",
          "date_of_birth",
          "zip_code",
          "pets"
          
        ]
      },
      "Pet":{
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "species": {
            "type": "string"
          },
          "carry": {
            "type": "string"
          },
          "weight": {
            "type": "number",
            "format": "float"
          },
          "date_of_birth": {
            "type": "string",
            "format": "date"
          }
        },
        "example": {
          "name": "Pet01",
          "species": "dog",
          "carry": "p",
          "weight": 5,
          "date_of_birth": "1993-12-12 10:10"
        },  
        "required": [
          "name",
          "species",
          "carry",
          "weight",
          "date_of_birth"
        ]
      },
      "PutPet":{
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "species": {
            "type": "string"
          },
          "carry": {
            "type": "string"
          },
          "weight": {
            "type": "number",
            "format": "float"
          },
          "date_of_birth": {
            "type": "string",
            "format": "date"
          }
        },
        "example": {
          "name": "Floquinho",
          "species": "dog",
          "carry": "p",
          "weight": 5,
          "date_of_birth": "1993-12-12 10:10"
        },  
        "required": [
          "name",
          "species",
          "carry",
          "weight",
          "date_of_birth"
        ]
      }
    },
    "securitySchemes":{
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}